import '../models/segment.dart';
import 'formulas/material_cost_estimator.dart';

class ProposalService {
  /// Drafts a formal FHWA/State funding proposal document based on segment quality metrics
  static String draftProposal(RoadSegment segment) {
    final estimation = MaterialCostEstimator.estimate(segment.distresses, segment.state);
    
    final agencyName = segment.state == 'FL' 
        ? 'Florida Department of Transportation (FDOT) District Office' 
        : 'Alabama Department of Transportation (ALDOT) Division Maintenance';
        
    final specRule = segment.state == 'FL'
        ? 'FDOT Pavement Condition Survey (PCS) Manual'
        : 'ALDOT Standard Specification Section 301 / Shoulder Maintenance';

    final defectsText = segment.distresses.isEmpty
        ? '* No significant pavement, shoulder, or striping defects logged.'
        : segment.distresses.map((d) => 
            '* Detected ${d.severity.name.toUpperCase()} severity ${d.specificType.replaceAll(RegExp(r'(?=[A-Z])'), ' ')}: ${d.quantity.toStringAsFixed(1)} ${d.unit}'
          ).join('\n');

    return '''# PROJECT FUNDING & MAINTENANCE PROPOSAL
**SUBMITTED TO:** $agencyName
**SUBMITTED BY:** Staxify, LLC (on behalf of Route Operations)
**DATE:** ${DateTime.now().toLocal().toString().split(' ')[0]}

---

## 1. Executive Summary
This document serves as a formal funding and authorization request for roadway resurfacing and safety repairs on **${segment.roadName.toUpperCase()}** (Milepost ${segment.startMilepost.toStringAsFixed(2)} to ${segment.endMilepost.toStringAsFixed(2)}). An automated computerized inspection was conducted on this ${segment.lengthInMiles.toStringAsFixed(2)}-mile segment, measuring physical roadway, shoulder, and traffic control mark distresses.

## 2. Segment Analysis & Ratings
Under standard compliance rulesets, the segment returned the following scores:
* **ASTM D6433 Pavement Condition Index (PCI):** ${segment.calculatedPci?.toStringAsFixed(1) ?? '100.0'} / 100
* **Estimated PASER Score:** ${segment.paserScore ?? 10} / 10
${segment.state == 'FL' ? '''* **FDOT Crack Rating:** ${segment.fdotCrackRating?.toStringAsFixed(1) ?? '10.0'} / 10
* **FDOT Rut Rating:** ${segment.fdotRutRating?.toStringAsFixed(1) ?? '10.0'} / 10''' : ''}

## 3. Logged Route Defects
The computerized vision scanner logged the following defect instances:
$defectsText

## 4. Statutory & FHWA Safety Justification
Under standard safety guidelines, maintenance action is requested due to:
* **AASHTO / FHWA Guidelines:** Safety drop-offs or structural rutting exceeding thresholds represent active hazard zones. Immediate structural correction is recommended to prevent vehicle rollovers and maintain pavement structural integrity.
* **DOT Compliance Standard:** Repairs must comply with **$specRule** standard guidelines.

## 5. Quantity Take-offs & Cost Estimates
Proposed material quantities and budgets to execute repair:
${estimation.materialList.map((m) => '* **${m.materialName}**: ${m.quantity.toStringAsFixed(1)} ${m.unit} (Est. cost \$${m.estimatedCost.toStringAsFixed(2)})').join('\n')}

**TOTAL REQUIRED FUNDING ALLOCATION: \$${estimation.totalEstimatedCost.toStringAsFixed(2)}**

---
*Generated by PaveSync AI (Staxify, LLC)*
''';
  }
}
